### ISSUE TITLE
Proje lisansı nedir?

### ISSUE THREAD

**Issue by hasansezertasan** [burakgarci/rastgele-profil#1]
Merhaba, şahane proje için teşekkürler 🙏.

Proje lisansı nedir? Projeyi ve içerisinde ki verileri kullanmakta herhangi bir kısıtlama mevcut mudur? Eğer kısıtlama yoksa bunu belli eden bir lisans dosyası ekleyebilir misiniz?

**Comment by burakgarci** [comment]
Merhaba, ilginiz için teşekkürler.

Proje lisansını **MIT License** olarak güncelledim. Bu lisans altında, projeyi kullanmak, dağıtmak, kopyalamak, değiştirmek ve ticari amaçlarla kullanmak gibi özgürlüklere sahipsiniz. 

Projeyi bu şekilde kullanmak isterseniz, kodların uzun süredir güncellenmediğini hatırlatmak isterim. 

İyi çalışmalar...

**Comment by hasansezertasan** [comment]
> Merhaba, ilginiz için teşekkürler.

🙏

> Proje lisansını **MIT License** olarak güncelledim. Bu lisans altında, projeyi kullanmak, dağıtmak, kopyalamak, değiştirmek ve ticari amaçlarla kullanmak gibi özgürlüklere sahipsiniz.

🚀 Süpersiniz 🚀 

> Projeyi bu şekilde kullanmak isterseniz, kodların uzun süredir güncellenmediğini hatırlatmak isterim.

Bilgilendirme için teşekkürler.

> İyi çalışmalar...

Teşekkürler, iyi çalışamalar 😇.
